In [1]:
import pandas as  pd

In [2]:
pd.Series()

Series([], dtype: float64)

In [8]:
L=[1,2,3,4,5,6]
print(L)

[1, 2, 3, 4, 5, 6]


In [9]:
Ser=pd.Series(L)
print(Ser)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [7]:
import numpy as np
Arr=np.array(L)
print(Arr)

[1 2 3 4 5 6]


In [10]:
Ser=pd.Series(L)
print(Ser)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [13]:
Ser.index

RangeIndex(start=0, stop=6, step=1)

In [14]:
Ser.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [15]:
Ser

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [17]:
pd.Series(L,index=[100,101,102,103,104,105])

100    1
101    2
102    3
103    4
104    5
105    6
dtype: int64

In [18]:
pd.Series(Arr)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [27]:
pd.Series(np.random.randint(100,140,10),index=np.arange(1,11),dtype=float)

1     110.0
2     114.0
3     138.0
4     137.0
5     100.0
6     122.0
7     135.0
8     108.0
9     107.0
10    101.0
dtype: float64

In [35]:
S=pd.Series(L,index=['a','b','c','d','e','f'])
S

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [36]:
S['a']

1

In [38]:
S[0]

1

In [39]:
S.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [40]:
S.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [41]:
D={'x':10,'y':20,'z':30}
pd.Series(D)

x    10
y    20
z    30
dtype: int64

In [46]:
data = {'a' : 0., 'b' : 1., 'c' : 2.}
pd.Series(data,index=['b','d','c','a'])

b    1.0
d    NaN
c    2.0
a    0.0
dtype: float64

In [47]:
pd.Series(7,index=np.arange(10))

0    7
1    7
2    7
3    7
4    7
5    7
6    7
7    7
8    7
9    7
dtype: int64

In [48]:
L

[1, 2, 3, 4, 5, 6]

In [49]:
pd.Series(L)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [59]:
df=pd.DataFrame(L,index=[1,2,3,4,5,6],columns=['Data'],dtype=float)
df

Data
1   1.0
2   2.0
3   3.0
4   4.0
5   5.0
6   6.0

In [57]:
df.index.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [58]:
df.values

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int64)

In [163]:
L=[['Ram',21,45.67],['Rohit',26,87.76],['Arpit',25,69.76]]
df=pd.DataFrame(L,columns=['Name','Age','Marks'])
df

Name  Age  Marks
0    Ram   21  45.67
1  Rohit   26  87.76
2  Arpit   25  69.76

In [164]:
df.Name

0      Ram
1    Rohit
2    Arpit
Name: Name, dtype: object

In [165]:
df['Name']

0      Ram
1    Rohit
2    Arpit
Name: Name, dtype: object

In [66]:
df[['Name']]

Name
0    Ram
1  Rohit
2  Arpit

In [68]:
df.iloc[:,0]

0      Ram
1    Rohit
2    Arpit
Name: Name, dtype: object

In [69]:
df.loc[:,'Name']

0      Ram
1    Rohit
2    Arpit
Name: Name, dtype: object

In [70]:
df.iloc[:,0:1]

Name
0    Ram
1  Rohit
2  Arpit

In [71]:
d={'Name':['abc','def','xyz'],'Age':[33,22,11],'Marks':[55.43,66.78,77.69]}
d

{'Name': ['abc', 'def', 'xyz'],
 'Age': [33, 22, 11],
 'Marks': [55.43, 66.78, 77.69]}

In [73]:
df=pd.DataFrame(d)
df

Name  Age  Marks
0  abc   33  55.43
1  def   22  66.78
2  xyz   11  77.69

In [74]:
df.to_csv('data.csv')

In [81]:
pd.DataFrame(df,columns=['Name','Mark','Dept'])

Name  Mark  Dept
0  abc   NaN   NaN
1  def   NaN   NaN
2  xyz   NaN   NaN

In [86]:
d = {'one'  : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df=pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [89]:
df['three']=pd.Series([10,11,12,13],index=['a','b','c','d'])

In [90]:
df

one  two  three
a  1.0    1     10
b  2.0    2     11
c  3.0    3     12
d  NaN    4     13

In [91]:
d = {'one'  : pd.Series([1, 2, 3],),
      'two' : pd.Series([1, 2, 3, 4])}

df=pd.DataFrame(d)
df

one  two
0  1.0    1
1  2.0    2
2  3.0    3
3  NaN    4

In [96]:
df['three']=pd.Series([10,11,12,13.])
df

one  two  three  Four
0  1.0    1   10.0  11.0
1  2.0    2   11.0  13.0
2  3.0    3   12.0  15.0
3  NaN    4   13.0   NaN

In [97]:
df['Four']=df['one']+df['three']
df

one  two  three  Four
0  1.0    1   10.0  11.0
1  2.0    2   11.0  13.0
2  3.0    3   12.0  15.0
3  NaN    4   13.0   NaN

In [99]:
df.one.sum()

6.0

In [102]:
df.iloc[3,0]+df.iloc[3,2]

nan

In [103]:
df

one  two  three  Four
0  1.0    1   10.0  11.0
1  2.0    2   11.0  13.0
2  3.0    3   12.0  15.0
3  NaN    4   13.0   NaN

In [104]:
del df['two']

In [105]:
df

one  three  Four
0  1.0   10.0  11.0
1  2.0   11.0  13.0
2  3.0   12.0  15.0
3  NaN   13.0   NaN

In [106]:
df.pop('three')

0    10.0
1    11.0
2    12.0
3    13.0
Name: three, dtype: float64

In [107]:
df

one  Four
0  1.0  11.0
1  2.0  13.0
2  3.0  15.0
3  NaN   NaN

In [111]:
df=df.drop(2)
df

one  Four
0  1.0  11.0
1  2.0  13.0
3  NaN   NaN

In [112]:
df

one  Four
0  1.0  11.0
1  2.0  13.0
3  NaN   NaN

In [113]:
Name=['Karan','Arpit','Varun','Akshay','Robin']
Age=[28,25,29,31,32]
Marks=[78,98,67,59,78]

In [116]:
Data=list(zip(Name,Age,Marks))
Data

[('Karan', 28, 78),
 ('Arpit', 25, 98),
 ('Varun', 29, 67),
 ('Akshay', 31, 59),
 ('Robin', 32, 78)]

In [119]:
df=pd.DataFrame(Data,columns=['Name','Age','Marks'])
df

Name  Age  Marks
0   Karan   28     78
1   Arpit   25     98
2   Varun   29     67
3  Akshay   31     59
4   Robin   32     78

In [120]:
pd.Series()

Series([], dtype: float64)

In [121]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [122]:
pd.Panel()

In [125]:
A1=np.random.randn(4,3)
A1

array([[-0.62943922, -0.37550728, -0.28379265],
       [ 0.46072235,  0.71317867, -0.64841553],
       [-0.16890961, -0.95335606, -1.64652632],
       [ 1.31942238, -0.67931758,  1.37584649]])

In [127]:
A2=np.random.randn(4,2)
A2

array([[-1.87358809, -0.60313132],
       [ 0.39252405,  0.37495167],
       [ 0.24006103, -0.53206266],
       [ 0.43674257,  0.0814035 ]])

In [128]:
df1=pd.DataFrame(A1)
df1

0         1         2
0 -0.629439 -0.375507 -0.283793
1  0.460722  0.713179 -0.648416
2 -0.168910 -0.953356 -1.646526
3  1.319422 -0.679318  1.375846

In [130]:
df2=pd.DataFrame(A2)
df2

0         1
0 -1.873588 -0.603131
1  0.392524  0.374952
2  0.240061 -0.532063
3  0.436743  0.081404

In [140]:
data1={'Item1':df1,'Item2':df2}

In [142]:
P = pd.Panel(data1)
P

TypeError: object() takes no parameters

In [146]:
!pip install xarray

  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1


You are using pip version 19.0.3, however version 20.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [147]:
df1.to_xarray()

<xarray.Dataset>
Dimensions:  (index: 4)
Coordinates:
  * index    (index) int64 0 1 2 3
Data variables:
    0        (index) float64 -0.6294 0.4607 -0.1689 1.319
    1        (index) float64 -0.3755 0.7132 -0.9534 -0.6793
    2        (index) float64 -0.2838 -0.6484 -1.647 1.376

In [170]:
d={'Name':pd.Series(['Akshay','Rajat','Robin','Kapil','James','Cyril']),'Age':pd.Series([25,26,29,27,23,21]),'Rating':pd.Series([4.23,2.35,1.56,3.20,4.62,3.99])}
df=pd.DataFrame(d)
df

Name  Age  Rating
0  Akshay   25    4.23
1   Rajat   26    2.35
2   Robin   29    1.56
3   Kapil   27    3.20
4   James   23    4.62
5   Cyril   21    3.99

In [171]:
df.sum()

Name      AkshayRajatRobinKapilJamesCyril
Age                                   151
Rating                              19.95
dtype: object

In [172]:
df.Age.sum()

151

In [173]:
df['Age'].sum()

151

In [174]:
df

Name  Age  Rating
0  Akshay   25    4.23
1   Rajat   26    2.35
2   Robin   29    1.56
3   Kapil   27    3.20
4   James   23    4.62
5   Cyril   21    3.99

In [175]:
df.Age.mean()

25.166666666666668

In [176]:
df.Age.std()

2.8577380332470415

In [177]:
df.Age.count()

6

In [178]:
df.Age.min()

21

In [179]:
df.Age.max()

29

In [180]:
df.Age.prod()

245822850

In [181]:
df.Age.median()

25.5

In [183]:
df.Age

0    25
1    26
2    29
3    27
4    23
5    21
Name: Age, dtype: int64

In [182]:
df.Age.cumsum()

0     25
1     51
2     80
3    107
4    130
5    151
Name: Age, dtype: int64

In [184]:
df.Age.cumprod()

0           25
1          650
2        18850
3       508950
4     11705850
5    245822850
Name: Age, dtype: int64

In [185]:
data=pd.read_csv('Suicidesindia2001-2012.csv')
data

State  Year      Type_code  \
0       A & N Islands  2001         Causes   
1       A & N Islands  2001         Causes   
2       A & N Islands  2001         Causes   
3       A & N Islands  2001         Causes   
4       A & N Islands  2001         Causes   
...               ...   ...            ...   
237514    West Bengal  2012  Social_Status   
237515    West Bengal  2012  Social_Status   
237516    West Bengal  2012  Social_Status   
237517    West Bengal  2012  Social_Status   
237518    West Bengal  2012  Social_Status   

                                           Type  Gender Age_group  Total  
0                            Illness (Aids/STD)  Female      0-14      0  
1       Bankruptcy or Sudden change in Economic  Female      0-14      0  
2       Cancellation/Non-Settlement of Marriage  Female      0-14      0  
3             Physical Abuse (Rape/Incest Etc.)  Female      0-14      0  
4                                 Dowry Dispute  Female      0-14      0  
...                                         ...     ...       ...    ...  
237514                                Seperated    Male    0-100+    149  
237515                          Widowed/Widower    Male    0-100+    233  
237516                                  Married    Male    0-100+   5451  
237517                                 Divorcee    Male    0-100+    189  
237518                            Never Married    Male    0-100+   2658  

[237519 rows x 7 columns]

In [186]:
pd.get_option("display.max_rows")

60

In [190]:
data.head(61)

State  Year Type_code                                     Type  \
0   A & N Islands  2001    Causes                       Illness (Aids/STD)   
1   A & N Islands  2001    Causes  Bankruptcy or Sudden change in Economic   
2   A & N Islands  2001    Causes  Cancellation/Non-Settlement of Marriage   
3   A & N Islands  2001    Causes        Physical Abuse (Rape/Incest Etc.)   
4   A & N Islands  2001    Causes                            Dowry Dispute   
..            ...   ...       ...                                      ...   
56  A & N Islands  2001    Causes  Bankruptcy or Sudden change in Economic   
57  A & N Islands  2001    Causes                                   Cancer   
58  A & N Islands  2001    Causes              Professional/Career Problem   
59  A & N Islands  2001    Causes                         Property Dispute   
60  A & N Islands  2001    Causes  Cancellation/Non-Settlement of Marriage   

    Gender Age_group  Total  
0   Female      0-14      0  
1   Female      0-14      0  
2   Female      0-14      0  
3   Female      0-14      0  
4   Female      0-14      0  
..     ...       ...    ...  
56  Female     15-29      0  
57  Female     15-29      0  
58  Female     15-29      0  
59  Female     15-29      0  
60  Female     15-29      0  

[61 rows x 7 columns]

In [192]:
pd.get_option("display.max_columns")

20

In [193]:
pd.set_option("display.max_rows",100)

In [194]:
pd.get_option("display.max_rows")

100

In [195]:
data.head(100)

State  Year Type_code                                      Type  \
0   A & N Islands  2001    Causes                        Illness (Aids/STD)   
1   A & N Islands  2001    Causes   Bankruptcy or Sudden change in Economic   
2   A & N Islands  2001    Causes   Cancellation/Non-Settlement of Marriage   
3   A & N Islands  2001    Causes         Physical Abuse (Rape/Incest Etc.)   
4   A & N Islands  2001    Causes                             Dowry Dispute   
5   A & N Islands  2001    Causes                           Family Problems   
6   A & N Islands  2001    Causes       Ideological Causes/Hero Worshipping   
7   A & N Islands  2001    Causes                   Other Prolonged Illness   
8   A & N Islands  2001    Causes                          Property Dispute   
9   A & N Islands  2001    Causes                 Fall in Social Reputation   
10  A & N Islands  2001    Causes                    Illegitimate Pregnancy   
11  A & N Islands  2001    Causes                    Failure in Examination   
12  A & N Islands  2001    Causes                   Insanity/Mental Illness   
13  A & N Islands  2001    Causes                              Love Affairs   
14  A & N Islands  2001    Causes               Professional/Career Problem   
15  A & N Islands  2001    Causes                                   Divorce   
16  A & N Islands  2001    Causes                      Drug Abuse/Addiction   
17  A & N Islands  2001    Causes  Not having Children(Barrenness/Impotency   
18  A & N Islands  2001    Causes                          Causes Not known   
19  A & N Islands  2001    Causes                              Unemployment   
20  A & N Islands  2001    Causes             Other Causes (Please Specity)   
21  A & N Islands  2001    Causes                                   Poverty   
22  A & N Islands  2001    Causes                      Death of Dear Person   
23  A & N Islands  2001    Causes                                    Cancer   
24  A & N Islands  2001    Causes                Suspected/Illicit Relation   
25  A & N Islands  2001    Causes                                 Paralysis   
26  A & N Islands  2001    Causes                          Property Dispute   
27  A & N Islands  2001    Causes                              Unemployment   
28  A & N Islands  2001    Causes                                   Poverty   
29  A & N Islands  2001    Causes                           Family Problems   
30  A & N Islands  2001    Causes                        Illness (Aids/STD)   
31  A & N Islands  2001    Causes                      Drug Abuse/Addiction   
32  A & N Islands  2001    Causes                   Other Prolonged Illness   
33  A & N Islands  2001    Causes                      Death of Dear Person   
34  A & N Islands  2001    Causes             Other Causes (Please Specity)   
35  A & N Islands  2001    Causes                                    Cancer   
36  A & N Islands  2001    Causes  Not having Children(Barrenness/Impotency   
37  A & N Islands  2001    Causes   Cancellation/Non-Settlement of Marriage   
38  A & N Islands  2001    Causes                          Causes Not known   
39  A & N Islands  2001    Causes                                 Paralysis   
40  A & N Islands  2001    Causes         Physical Abuse (Rape/Incest Etc.)   
41  A & N Islands  2001    Causes               Professional/Career Problem   
42  A & N Islands  2001    Causes                              Love Affairs   
43  A & N Islands  2001    Causes                 Fall in Social Reputation   
44  A & N Islands  2001    Causes                             Dowry Dispute   
45  A & N Islands  2001    Causes       Ideological Causes/Hero Worshipping   
46  A & N Islands  2001    Causes                    Illegitimate Pregnancy   
47  A & N Islands  2001    Causes                    Failure in Examination   
48  A & N Islands  2001    Causes   Bankruptcy or Sudden change in Economic   
49  A & N Islands  2001    Causes                   Insanity/M

In [196]:
pd.set_option("display.max_columns",30)

In [197]:
pd.get_option("display.max_columns")

30

In [198]:
pd.reset_option("display.max_row")

In [199]:
pd.get_option("display.max_rows")

60

In [200]:
pd.reset_option('display.max_columns')

In [201]:
pd.get_option('display.max_columns')

20